### ISSUE TITLE
False positives on tracker list

### ISSUE THREAD

**Issue by CollinChaffin** [cbuijs/airelle#1]
I was frankly blown away to find `www.petri.com` contained in the tracker list as this is (and has been for literally DECADES) a MAJOR and very reputable technology information site.  I have heard other avoid this list citing many other similar issues and I do not see any indications whether this is in fact the correct place to open this issue but hopefully it is and this domain can be reconsidered (or explain to me what I'm missing) because I truly do believe in making every attempt to make any/all of these blocklists as helpful and accurate as possible.  Thanks for providing!

**Comment by cbuijs** [comment]
Hi @CollinChaffin ,

Thanks for reporting and providing information.

Unfortunately, I am not the maintainer of the source of the lists (see here for the source: http://rlwpx.free.fr/WPFF/hosts.htm).

I suggest that you contact the maintainer (http://rlwpx.free.fr/WPFF/mel.htm), to report directly.

The version of the lists here are just an "unpacked" and "optimized" version, there are no modifications, additions or exclusions made.

**As sidenote:** I know this lists are rather "inclusive" and breaks a lot of sites. This is a know issue in the "community" as you said yourself as well. These lists are actually meant to be quite extreme in blocking stuff. I would suggest only to use the porn- and malware-list as most "unbreakable" for adult/smut/bad sites etc. The rest will certainly break things.

Hope this helps.

Cheers,
-Chris.
