### ISSUE TITLE
False positive malware: duo.nl

### ISSUE THREAD

**Issue by simon5738** [cbuijs/airelle#2]
Duo.nl is a Dutch domain for Ministry of Education and not a site for malware hosting :)

Thank you for the list and the update!

**Comment by cbuijs** [comment]
hi @simon5738,

Thanks for reporting and providing information.

Unfortunately, I am not the maintainer of the source of the lists (see here for the source: http://rlwpx.free.fr/WPFF/hosts.htm).

I suggest that you contact the maintainer (http://rlwpx.free.fr/WPFF/mel.htm), to report directly.

The version of the lists here are just an "unpacked" and "optimized" version, there are no modifications, additions or exclusions made.

As sidenote: I know this lists are rather "inclusive" and break a lot of sites. This is a know issue in the "community". These lists are actually meant to be quite extreme in blocking stuff. I would suggest only to use the porn- and malware-list as most "unbreakable" for adult/smut/bad sites etc. The rest will certainly break things.

Hope this helps.

Cheers,
-Chris.
